-- CreateTable
CREATE TABLE "temples" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "city" "City" NOT NULL,
    "fullAddress" TEXT NOT NULL,
    "landmark" TEXT,
    "description" TEXT NOT NULL,
    "shortDesc" TEXT,
    "latitude" DOUBLE PRECISION,
    "longitude" DOUBLE PRECISION,
    "deityName" TEXT NOT NULL,
    "templeType" TEXT,
    "builtYear" TEXT,
    "founder" TEXT,
    "mythologicalSignificance" TEXT,
    "historicalSignificance" TEXT,
    "architectureStyle" TEXT,
    "uniqueFeatures" TEXT,
    "sacredNearby" TEXT,
    "associatedLegends" TEXT,
    "darshanTimings" JSONB NOT NULL,
    "morningAarti" TEXT,
    "afternoonAarti" TEXT,
    "eveningAarti" TEXT,
    "specialSevas" TEXT,
    "festivalSpecificTimings" TEXT,
    "generalEntryFee" TEXT,
    "specialDarshanFee" TEXT,
    "vipDarshanFee" TEXT,
    "parkingAvailable" BOOLEAN NOT NULL DEFAULT false,
    "wheelchairAccessible" BOOLEAN NOT NULL DEFAULT false,
    "cloakroomAvailable" BOOLEAN NOT NULL DEFAULT false,
    "restroomsAvailable" BOOLEAN NOT NULL DEFAULT false,
    "drinkingWaterAvailable" BOOLEAN NOT NULL DEFAULT false,
    "prasadamCounterAvailable" BOOLEAN NOT NULL DEFAULT false,
    "photographyAllowed" BOOLEAN NOT NULL DEFAULT true,
    "mobileRestrictions" TEXT,
    "dressCodeMen" TEXT,
    "dressCodeWomen" TEXT,
    "securityNotes" TEXT,
    "majorFestivals" TEXT,
    "festivalDates" TEXT,
    "annualBrahmotsavam" TEXT,
    "rathotsavamDetails" TEXT,
    "crowdExpectationLevel" TEXT,
    "specialPoojas" TEXT,
    "specialDecorationDays" TEXT,
    "bestMonths" TEXT,
    "bestTimeOfDay" TEXT,
    "peakCrowdDays" TEXT,
    "avoidDays" TEXT,
    "weatherConditions" TEXT,
    "nearbyTemples" TEXT,
    "nearbyBeachesOrHills" TEXT,
    "nearbyRestaurants" TEXT,
    "nearbyHotels" TEXT,
    "distanceRailwayStation" TEXT,
    "distanceBusStand" TEXT,
    "distanceAirport" TEXT,
    "images" JSONB NOT NULL,
    "videos" JSONB,
    "virtualTourUrl" TEXT,
    "metaTitle" TEXT,
    "metaDescription" TEXT,
    "searchKeywords" TEXT,
    "canonicalUrl" TEXT,
    "openGraphImage" TEXT,
    "structuredDataJsonLd" TEXT,
    "devoteeTips" TEXT,
    "thingsToCarry" TEXT,
    "thingsNotAllowed" TEXT,
    "idealVisitDuration" TEXT,
    "suggestedItinerary" TEXT,
    "localFoodRecommendations" TEXT,
    "faqs" JSONB,
    "emergencyContact" TEXT,
    "templeOfficePhone" TEXT,
    "lostAndFoundDesk" TEXT,
    "medicalFacilityNearby" TEXT,
    "policeStationNearby" TEXT,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "temples_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "temples_slug_key" ON "temples"("slug");

-- CreateIndex
CREATE INDEX "temples_city_idx" ON "temples"("city");

-- CreateIndex
CREATE INDEX "temples_active_idx" ON "temples"("active");
